apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol05
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/exports/vol05
    server: services.lab.example.com
